// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrzmQ8qnOyBQs9QYovmvbIAGigRyQ1Hp0',
    appId: '1:825187216258:web:df9bbf02bd9311407e3d9b',
    messagingSenderId: '825187216258',
    projectId: 'webnyou-flow-link',
    authDomain: 'webnyou-flow-link.firebaseapp.com',
    storageBucket: 'webnyou-flow-link.firebasestorage.app',
    measurementId: 'G-4BNC4C2VDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy8LNwGc3lUswXOz7QWPPmj3mngbEYIeo',
    appId: '1:825187216258:android:2ad99c490ff6cf737e3d9b',
    messagingSenderId: '825187216258',
    projectId: 'webnyou-flow-link',
    storageBucket: 'webnyou-flow-link.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF5Ja5kLhLOgm-M7g175XtHTbyBGzSh-s',
    appId: '1:825187216258:ios:7e294800b26cc0657e3d9b',
    messagingSenderId: '825187216258',
    projectId: 'webnyou-flow-link',
    storageBucket: 'webnyou-flow-link.firebasestorage.app',
    androidClientId: '825187216258-4aqr43ha3ahonnacad1oj3gq6fea5bo2.apps.googleusercontent.com',
    iosClientId: '825187216258-q0dspbtjb7h2oqhriegucq89pf9bgq4e.apps.googleusercontent.com',
    iosBundleId: 'com.jiwabakti.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF5Ja5kLhLOgm-M7g175XtHTbyBGzSh-s',
    appId: '1:825187216258:ios:cbfc5d68b93f31e87e3d9b',
    messagingSenderId: '825187216258',
    projectId: 'webnyou-flow-link',
    storageBucket: 'webnyou-flow-link.firebasestorage.app',
    androidClientId: '825187216258-4aqr43ha3ahonnacad1oj3gq6fea5bo2.apps.googleusercontent.com',
    iosClientId: '825187216258-0hi0bm0j9jt2arp23b0fv3d5s0r425a9.apps.googleusercontent.com',
    iosBundleId: 'com.jiwabakti.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrzmQ8qnOyBQs9QYovmvbIAGigRyQ1Hp0',
    appId: '1:825187216258:web:7b7d0af11df6f45a7e3d9b',
    messagingSenderId: '825187216258',
    projectId: 'webnyou-flow-link',
    authDomain: 'webnyou-flow-link.firebaseapp.com',
    storageBucket: 'webnyou-flow-link.firebasestorage.app',
    measurementId: 'G-B9RPG4H3ZF',
  );

}